# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nuser.proto\"\'\n\x07Teacher\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x63ourse\x18\x02 \x03(\tB\tZ\x07.;protob\x06proto3')

_TEACHER = DESCRIPTOR.message_types_by_name['Teacher']
Teacher = _reflection.GeneratedProtocolMessageType('Teacher', (_message.Message,), {
    'DESCRIPTOR': _TEACHER,
    '__module__': 'user_pb2'
    # @@protoc_insertion_point(class_scope:Teacher)
})
_sym_db.RegisterMessage(Teacher)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'Z\007.;proto'
    _TEACHER._serialized_start = 14
    _TEACHER._serialized_end = 53
# @@protoc_insertion_point(module_scope)
