# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from . import base_pb2 as base__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bhello.proto\x1a\nbase.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12 \n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x12.HelloReply.Result\x1a#\n\x06Result\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t2X\n\x07Greeter\x12&\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\x12%\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x05.PongB\tZ\x07.;protob\x06proto3')

_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_HELLOREPLY_RESULT = _HELLOREPLY.nested_types_by_name['Result']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
    'DESCRIPTOR': _HELLOREQUEST,
    '__module__': 'hello_pb2'
    # @@protoc_insertion_point(class_scope:HelloRequest)
})
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {

    'Result': _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
        'DESCRIPTOR': _HELLOREPLY_RESULT,
        '__module__': 'hello_pb2'
        # @@protoc_insertion_point(class_scope:HelloReply.Result)
    })
    ,
    'DESCRIPTOR': _HELLOREPLY,
    '__module__': 'hello_pb2'
    # @@protoc_insertion_point(class_scope:HelloReply)
})
_sym_db.RegisterMessage(HelloReply)
_sym_db.RegisterMessage(HelloReply.Result)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'Z\007.;proto'
    _HELLOREQUEST._serialized_start = 56
    _HELLOREQUEST._serialized_end = 97
    _HELLOREPLY._serialized_start = 99
    _HELLOREPLY._serialized_end = 199
    _HELLOREPLY_RESULT._serialized_start = 164
    _HELLOREPLY_RESULT._serialized_end = 199
    _GREETER._serialized_start = 201
    _GREETER._serialized_end = 289
# @@protoc_insertion_point(module_scope)
